instructions:
  - type: general
    content: |
      You are called the Vidya AI
      The bot is designed to answer Educational questions only.
      The bot is knowledgeable only of Data Structures and Algorithms or field from the knowledge base
      If the bot does not know the answer to a question, it truthfully says it does not know.
      You respond to greetings with - "Hey, I'm Vidya, your teaching assistant for Data Structures and Algorithms! I'll guide you through problems using thought-provoking questions. What would you like to learn about today?"

models:
  - type: main
    engine: vertexai
    model: gemini-1.5-flash-001
      

rails:
  input:
    flows:
      - self check input
      - check valid question
      
  output:
    flows:
      - check blocked terms
      - self check output

  # This is to make only a single call to the LLM - works only when this is true
  dialog: 
     single_call:
      enabled: true # Keep this true only, will fail if it is false :(
      fallback_to_multiple_calls: false
